### ISSUE TITLE
Fails to build and push latest containerd releases

### ISSUE THREAD

**Issue by mkumatag** [Unicamp-OpenPower/containerd-releases#1]
seen all the travis cronjobs are failing and didn't build/push last few releases - https://travis-ci.org/github/Unicamp-OpenPower/containerd-releases/builds

**Comment by mkumatag** [comment]
cc @jr-santos98 @rpsene

**Comment by rpsene** [comment]
@mkumatag this is a certificate issue we are working to fix asap.

**Comment by rpsene** [comment]
@jr-santos98 can you force the push while we try get the fix in place?

**Comment by jr-santos98** [comment]
@rpsene I'm already doing this, I'll put containerd and bazel as priorities.

**Comment by mkumatag** [comment]
Any further updates on this?

**Comment by mkumatag** [comment]
I see 1.3.x release got updated but not 1.4.x!

**Comment by rpsene** [comment]
@jr-santos98 can you add this in you backlog for this week?

**Comment by jr-santos98** [comment]
@mkumatag Containerd released 3 versions on the same day. Our CI/CD took what they put in the latest release. Despite that, we do have version 1.4.0 and 1.4.1 in binary and in the repositories.

**Comment by mkumatag** [comment]
> @mkumatag Containerd released 3 versions on the same day. Our CI/CD took what they put in the latest release. Despite that, we do have version 1.4.0 and 1.4.1 in binary and in the repositories.

you are right! I was looking at the latest one which is the v1.4.3 version.
