### ISSUE TITLE
Ship cri-release and cri-cni-release also

### ISSUE THREAD

**Issue by mkumatag** [Unicamp-OpenPower/containerd-releases#2]
Right now I see the following archives,
<img width="646" alt="image" src="https://user-images.githubusercontent.com/12646029/142758374-df289cf0-7d6b-4549-9f49-485200fdb587.png">
From: https://oplab9.parqtec.unicamp.br/pub/ppc64el/containerd/containerd-1.5.7/

Please ship the following tars as well:

```
cri-containerd-1.5.7-linux-ppc64le.tar.gz
cri-containerd-1.5.7-linux-ppc64le.tar.gz.sha256sum
cri-containerd-cni-1.5.7-linux-ppc64le.tar.gz
cri-containerd-cni-1.5.7-linux-ppc64le.tar.gz.sha256sum
```

**Comment by mkumatag** [comment]
cc @rpsene

**Comment by rpsene** [comment]
@jr-santos98 can you handle it?

**Comment by jr-santos98** [comment]
Hello @mkumatag 
The requested packages are saved in another folder.
To access containerd-cri, use the link:
https://oplab9.parqtec.unicamp.br/pub/ppc64el/containerd-cri/
Version 1.5.8 now available for containerd and cri.

**Comment by mkumatag** [comment]
> Hello @mkumatag
> The requested packages are saved in another folder.
> To access containerd-cri, use the link:
> https://oplab9.parqtec.unicamp.br/pub/ppc64el/containerd-cri/
> Version 1.5.8 now available for containerd and cri.

okay, thanks

**Comment by mkumatag** [comment]
this can be closed.
